name: CI

on: [push, pull_request]

jobs:
  run:
    name: "Build static files with Racket '${{ matrix.racket-version }}' (${{ matrix.racket-variant }})"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        racket-version: ["6.12", "7.9", "8.4", "current"]
        racket-variant: ["BC", "CS"]
        # CS builds are only provided for versions 7.4 and up so avoid
        # running the job for prior versions.
        exclude:
          - {racket-version: "6.12",   racket-variant: "CS"}

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - uses: Bogdanp/setup-racket@v0.11
      with:
        distribution: 'full'
        version: ${{ matrix.racket-version }}
        variant: ${{ matrix.racket-variant }}

    - name: Install Pollen and its dependencies
      run: raco pkg install --auto --batch

    - name: Run the tests
      run: xvfb-run raco test -j 4 -p pollen

    - name: Build static files
      run: raco pollen render